// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Data;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication3.Models.Brans", b =>
                {
                    b.Property<int>("Brans_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Brans_Id"), 1L, 1);

                    b.Property<string>("Brans_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Brans_Id");

                    b.ToTable("brans");
                });

            modelBuilder.Entity("WebApplication3.Models.ilcesi", b =>
                {
                    b.Property<int>("ilce_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ilce_Id"), 1L, 1);

                    b.Property<int>("il_Id")
                        .HasColumnType("int");

                    b.Property<string>("ilce_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("iliil_Id")
                        .HasColumnType("int");

                    b.HasKey("ilce_Id");

                    b.HasIndex("iliil_Id");

                    b.ToTable("ilcesis");
                });

            modelBuilder.Entity("WebApplication3.Models.ili", b =>
                {
                    b.Property<int>("il_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("il_Id"), 1L, 1);

                    b.Property<string>("il_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("il_Id");

                    b.ToTable("ilis");
                });

            modelBuilder.Entity("WebApplication3.Models.Okul", b =>
                {
                    b.Property<int>("Okul_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Okul_Id"), 1L, 1);

                    b.Property<string>("OkulAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VergiNo")
                        .HasColumnType("int");

                    b.Property<int>("ilce_Id")
                        .HasColumnType("int");

                    b.HasKey("Okul_Id");

                    b.ToTable("Okuls");
                });

            modelBuilder.Entity("WebApplication3.Models.ilcesi", b =>
                {
                    b.HasOne("WebApplication3.Models.ili", "ili")
                        .WithMany("ilcesis")
                        .HasForeignKey("iliil_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ili");
                });

            modelBuilder.Entity("WebApplication3.Models.ili", b =>
                {
                    b.Navigation("ilcesis");
                });
#pragma warning restore 612, 618
        }
    }
}
